name: Index urls to Google

on:
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Store google api credential to a file
        run: echo "${{ secrets.GOOGLE_API_CREDENTIAL }}" >> cred.json

      - name: Run the script
        run: python main.py -i urls.txt -e successful.txt -c cred.json

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add new urls to successful.json"
